Step-10A: Style Task Card
sta-wtag/TodoApp pull request #12
Opened 2023-02-05 09:33 UTC by sta-wtag

### **[Step-10A](https://trello.com/c/1tRkXyUL/8-step-10a-style-task-card)**

Add styling to Task Card.

### Acceptance Criteria

1.Add styling to Task cards according to [design](https://www.figma.com/file/9Rwb2k9Dfbh8Ycb6kbJfzZ/Todo-App-UI-for-New-Joiner?node-id=0%3A1&t=fqQdwByuj6siGx5y-0).

2023-02-07 06:13 UTC, hhu-wtag approved these changes

2023-02-07 06:13 UTC, hhu-wtag commented on assets/css/main.css
> +  color:White
Typo? 
```suggestion
  color: white
```

2023-02-07 06:13 UTC, hhu-wtag commented on components/TaskCard.vue
> +      swal('Changes are saved successfully', {
Please use i18n here

2023-02-07 06:13 UTC, hhu-wtag commented on components/TaskContainer.vue
> +        swal('Field is empty', {
Ditto

2023-02-07 06:13 UTC, hhu-wtag commented on components/TaskContainer.vue
> +      swal('Changes are saved successfully', {
Ditto

2023-02-07 06:13 UTC, hhu-wtag commented on helpers/helper.js
> +    }
```suggestion
    return val ? format(new Date(val), 'dd.MM.yyyy') : undefined
```

2023-02-20 05:17 UTC, sai-wtag approved these changes
Locally tested. LGTM. Nice Work. Thanks

2023-02-21 16:18 UTC, sta-wtag commented on assets/css/main.css
> +  color:White
Resolved

2023-02-21 16:18 UTC, sta-wtag commented on components/TaskCard.vue
> +      swal('Changes are saved successfully', {
resolved

2023-02-26 04:47 UTC, bia-wtag requested changes
Tested locally. Could you please have a look at the following issues?

- Task card style is broken for long titles. Please use a max-width along with consideration for a long title.
![Screenshot 2023-02-26 at 10 44 26 AM](https://user-images.githubusercontent.com/85149436/221392819-3c1c047a-ed56-454c-861f-6a31ef543079.png)

- Layout and card style broken for mobile, that is, it's scrollable vertically.
![Screenshot 2023-02-26 at 10 47 31 AM](https://user-images.githubusercontent.com/85149436/221392863-dfb04037-2669-4363-b43d-ce32531724ae.png)

2023-03-15 07:42 UTC, bia-wtag approved these changes

2023-03-26 02:41 UTC, merged